### ISSUE TITLE
alternative to torrent for getting model weights

### ISSUE THREAD

**Issue by Joel-Bauer** [lRomul/sensorium#1]
Hi lRomul,
Thanks for sharing all your code! Is there another way of getting the model weights. I've been waiting for a few days for a peer, but uTorrent has not found any.

**Comment by lRomul** [comment]
Hello! I restarted old seed machine and added new one. Can you try again, please?
If the problem is not solved, I will add some other method. The torrent was used simply because I ran out of limits on services like Google Drive. I will need to find an alternative.

**Comment by Joel-Bauer** [comment]
Hi,
Yea the download worked. Thanks alot!
